name: ONDC:NTS10
versions:
  - id: 2.0.0
    reporting: false
    usecase:
      - name: RECONCILIATION
        flows: "./v-2.0.0/RECONCILIATION/flows/index.yaml"
    supportedActions:
      $ref: "src/config/NTS10/v-2.0.0/supportedActions/index.yaml"