supportedActions:
  "": ["recon"]
  "null": ["recon"]
  recon: ["on_recon"]
  on_recon: [""]

apiProperties:
  recon:
    async_predecessor: null
    transaction_partner: []
  on_recon:
    async_predecessor: recon
    transaction_partner: ["recon"]