name: ONDC:RET18
versions:
  - id: 1.2.0
    reporting: false
    supportedActions:
      $ref: src/config/RET18/V-1.2.0/supportedActions/index.yaml
    usecase:
      - name: HEALTH&WELLNESS
        flows: /V-1.2.0/Health&Wellness/flows/index.yaml
  - id: 1.2.5
    reporting: false
    supportedActions:
      $ref: src/config/RET18/V-1.2.5/supportedActions/index.yaml
    usecase:
      - name: HEALTH&WELLNESS
        flows: /V-1.2.5/Health&Wellness/flows/index.yaml
